### ISSUE TITLE
Question about the result of the /healthz at the README file

### ISSUE THREAD

**Issue by BoraBak** [MEDIGO/go-healthz#3]
Calling `/healthz` prints the result shown in the README file.
Some questions regards:

1. What does `healthz.Register(name string, period time.Duration, fn CheckFunc) do? Meaning, when does the `fn CheckFunc` start? Is it being executed after the `period` time ends?
2. Why does the status bein printed is `"Unavailable"`?
3. Why do we have `"failures"`?

**Comment by BoraBak** [comment]
@dbrabera any insights?

**Comment by eggman64** [comment]
Hi @BoraBak


> 1. What does `healthz.Register(name string, period time.Duration, fn CheckFunc) do? Meaning, when does the `fn CheckFunc`start? Is it being executed after the`period` time ends?

Yes. `Register` registers a check to be evaluated each given `period`. With this method, you can add application specific checks. For example, a database connection check, an essential third-party dependency checks, etc.

> 2. Why does the status bein printed is `"Unavailable"`?

This is standard 503 protocol response https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
 
> 3. Why do we have `"failures"`?

`failures` passes the errors from the `CheckFunc`
